id: P000314
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6248
  title: རེབ་ཀོང་རུས་མཛོད་ལྟ་བ་མཁའ་ཁྱབ་ཕྱོགས་བྲལ།
  author: ''
  volumes:
    39910f4d51194ea2927a666bede3e58c:
      image_group_id: I1KG10627
      title: Volume 1 of reb kong rus mdzod lta ba mkha' khyab phyogs bral/
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
ebook_metadata:
  title: རེབ་ཀོང་རུས་མཛོད་ལྟ་བ་མཁའ་ཁྱབ་ཕྱོགས་བྲལ།
  author: ''
  sku: P000314
  cover: cover.jpg
  layers:
  - pagination
